name: Subspace

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  subspace-win32:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd subspace
          cmake --preset subspace-win32
        
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd subspace
          cmake --build --preset subspace-win32-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subspace-win32-exe
          path: build/subspace-win32/Release/*

  subspace-win64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
               
      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd subspace
          cmake --preset subspace-win64
        
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd subspace
          cmake --build --preset subspace-win64-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subspace-win64-exe
          path: build/subspace-win64/Release/*

  game-win32:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd game
          cmake --preset game-win32
        
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd game
          cmake --build --preset game-win32-release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-win32-exe
          path: build/game-win32/Release/*

  subspace-mkdat:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd subspace
          cmake --preset subspace-win64
        
      - name: Build mkdat
        working-directory: subspace
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd subspace
          cmake --build --preset subspace-win64-release --target mkdat
        
      - name: Build subspace.dat
        run: build/subspace-win64/tools/Release/mkdat.exe subspace.dat data

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subspace-dat
          path: subspace.dat

  package-artifacts-win32:
    runs-on: windows-latest
    needs: [subspace-win32, game-win32, subspace-mkdat]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Move necessary files to package directory
        run: |
          mkdir package
          mv subspace-win32/subspace.exe package/
          mv game-win32/subspacegame.exe package/
          mv subspace-dat/subspace.dat package/

      - name: Create zip file
        run: powershell Compress-Archive -Path package/* -DestinationPath subspace-win32.zip

      - name: Upload final zip
        uses: actions/upload-artifact@v4
        with:
          name: subspace-win32
          path: subspace-win32.zip

  package-artifacts-win64:
    runs-on: windows-latest
    needs: [subspace-win64, game-win32, subspace-mkdat]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Move necessary files to package directory
        run: |
          mkdir package
          mv subspace-win64/subspace.exe package/
          mv game-win32/subspacegame.exe package/
          mv subspace-dat/subspace.dat package/

      - name: Create zip file
        run: powershell Compress-Archive -Path package/* -DestinationPath subspace-win64.zip

      - name: Upload final zip
        uses: actions/upload-artifact@v4
        with:
          name: subspace-win64
          path: subspace-win64.zip
